/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INSANE_PROGRAM_H_RPCGEN
#define _INSANE_PROGRAM_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>
#include <stdlib.h>
#include <stdio.h>

struct num_arg_1 {
	u_int arg1;
	u_int arg2;
};
typedef struct num_arg_1 num_arg_1;
#ifdef __cplusplus
extern "C" bool_t xdr_num_arg_1(XDR *, num_arg_1*);
#elif __STDC__
extern  bool_t xdr_num_arg_1(XDR *, num_arg_1*);
#else /* Old Style C */
bool_t xdr_num_arg_1();
#endif /* Old Style C */


struct num_arg_2 {
	u_int arg1;
	u_int arg2;
	u_int arg3;
};
typedef struct num_arg_2 num_arg_2;
#ifdef __cplusplus
extern "C" bool_t xdr_num_arg_2(XDR *, num_arg_2*);
#elif __STDC__
extern  bool_t xdr_num_arg_2(XDR *, num_arg_2*);
#else /* Old Style C */
bool_t xdr_num_arg_2();
#endif /* Old Style C */


struct num_arg_3 {
	u_int arg1;
	u_int arg2;
	u_char *arg_name;
};
typedef struct num_arg_3 num_arg_3;
#ifdef __cplusplus
extern "C" bool_t xdr_num_arg_3(XDR *, num_arg_3*);
#elif __STDC__
extern  bool_t xdr_num_arg_3(XDR *, num_arg_3*);
#else /* Old Style C */
bool_t xdr_num_arg_3();
#endif /* Old Style C */


#define NUMBER ((rpc_uint)0x23330001)
#define ADD_SUB ((rpc_uint)1)

#ifdef __cplusplus
#define add_numbers ((rpc_uint)1)
extern "C" int * add_numbers_1(num_arg_1 *, CLIENT *);
extern "C" int * add_numbers_1_svc(num_arg_1 *, struct svc_req *);
#define add_numbers_name ((rpc_uint)2)
extern "C" int * add_numbers_name_1(num_arg_3 *, CLIENT *);
extern "C" int * add_numbers_name_1_svc(num_arg_3 *, struct svc_req *);
#define sub_numbers ((rpc_uint)3)
extern "C" int * sub_numbers_1(num_arg_1 *, CLIENT *);
extern "C" int * sub_numbers_1_svc(num_arg_1 *, struct svc_req *);
#define sub_numbers_name ((rpc_uint)4)
extern "C" int * sub_numbers_name_1(num_arg_3 *, CLIENT *);
extern "C" int * sub_numbers_name_1_svc(num_arg_3 *, struct svc_req *);

#elif __STDC__
#define add_numbers ((rpc_uint)1)
extern  int * add_numbers_1(num_arg_1 *, CLIENT *);
extern  int * add_numbers_1_svc(num_arg_1 *, struct svc_req *);
#define add_numbers_name ((rpc_uint)2)
extern  int * add_numbers_name_1(num_arg_3 *, CLIENT *);
extern  int * add_numbers_name_1_svc(num_arg_3 *, struct svc_req *);
#define sub_numbers ((rpc_uint)3)
extern  int * sub_numbers_1(num_arg_1 *, CLIENT *);
extern  int * sub_numbers_1_svc(num_arg_1 *, struct svc_req *);
#define sub_numbers_name ((rpc_uint)4)
extern  int * sub_numbers_name_1(num_arg_3 *, CLIENT *);
extern  int * sub_numbers_name_1_svc(num_arg_3 *, struct svc_req *);

#else /* Old Style C */
#define add_numbers ((rpc_uint)1)
extern  int * add_numbers_1();
extern  int * add_numbers_1_svc();
#define add_numbers_name ((rpc_uint)2)
extern  int * add_numbers_name_1();
extern  int * add_numbers_name_1_svc();
#define sub_numbers ((rpc_uint)3)
extern  int * sub_numbers_1();
extern  int * sub_numbers_1_svc();
#define sub_numbers_name ((rpc_uint)4)
extern  int * sub_numbers_name_1();
extern  int * sub_numbers_name_1_svc();
#endif /* Old Style C */
#define MULT_DIV ((rpc_uint)2)

#ifdef __cplusplus
#define mult_numbers ((rpc_uint)1)
extern "C" int * mult_numbers_2(num_arg_1 *, CLIENT *);
extern "C" int * mult_numbers_2_svc(num_arg_1 *, struct svc_req *);
#define mult_numbers_name ((rpc_uint)2)
extern "C" int * mult_numbers_name_2(num_arg_3 *, CLIENT *);
extern "C" int * mult_numbers_name_2_svc(num_arg_3 *, struct svc_req *);
#define div_numbers ((rpc_uint)3)
extern "C" int * div_numbers_2(num_arg_1 *, CLIENT *);
extern "C" int * div_numbers_2_svc(num_arg_1 *, struct svc_req *);
#define div_numbers_name ((rpc_uint)4)
extern "C" int * div_numbers_name_2(num_arg_3 *, CLIENT *);
extern "C" int * div_numbers_name_2_svc(num_arg_3 *, struct svc_req *);

#elif __STDC__
#define mult_numbers ((rpc_uint)1)
extern  int * mult_numbers_2(num_arg_1 *, CLIENT *);
extern  int * mult_numbers_2_svc(num_arg_1 *, struct svc_req *);
#define mult_numbers_name ((rpc_uint)2)
extern  int * mult_numbers_name_2(num_arg_3 *, CLIENT *);
extern  int * mult_numbers_name_2_svc(num_arg_3 *, struct svc_req *);
#define div_numbers ((rpc_uint)3)
extern  int * div_numbers_2(num_arg_1 *, CLIENT *);
extern  int * div_numbers_2_svc(num_arg_1 *, struct svc_req *);
#define div_numbers_name ((rpc_uint)4)
extern  int * div_numbers_name_2(num_arg_3 *, CLIENT *);
extern  int * div_numbers_name_2_svc(num_arg_3 *, struct svc_req *);

#else /* Old Style C */
#define mult_numbers ((rpc_uint)1)
extern  int * mult_numbers_2();
extern  int * mult_numbers_2_svc();
#define mult_numbers_name ((rpc_uint)2)
extern  int * mult_numbers_name_2();
extern  int * mult_numbers_name_2_svc();
#define div_numbers ((rpc_uint)3)
extern  int * div_numbers_2();
extern  int * div_numbers_2_svc();
#define div_numbers_name ((rpc_uint)4)
extern  int * div_numbers_name_2();
extern  int * div_numbers_name_2_svc();
#endif /* Old Style C */

#endif /* !_INSANE_PROGRAM_H_RPCGEN */
