/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "insane_program.h"


void
number_1( char* host )
{
	CLIENT *clnt;
	int  *result_1;
	num_arg_1  add_numbers_1_arg;
        add_numbers_1_arg.arg1 = 22;
        add_numbers_1_arg.arg2 = 22;
//	int  *result_2;
//	num_arg_3  add_numbers_name_1_arg;
//	int  *result_3;
//	num_arg_1  sub_numbers_1_arg;
//	int  *result_4;
//	num_arg_3  sub_numbers_name_1_arg;
	clnt = clnt_create(host, NUMBER, ADD_SUB, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = add_numbers_1(&add_numbers_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
//	result_2 = add_numbers_name_1(&add_numbers_name_1_arg, clnt);
//	if (result_2 == NULL) {
//		clnt_perror(clnt, "call failed:");
//	}
//	result_3 = sub_numbers_1(&sub_numbers_1_arg, clnt);
//	if (result_3 == NULL) {
//		clnt_perror(clnt, "call failed:");
//	}
//	result_4 = sub_numbers_name_1(&sub_numbers_name_1_arg, clnt);
//	if (result_4 == NULL) {
//		clnt_perror(clnt, "call failed:");
//	}
	clnt_destroy( clnt );
}


void
number_2( char* host )
{
	CLIENT *clnt;
	int  *result_1;
	num_arg_1  mult_numbers_2_arg;
	int  *result_2;
	num_arg_3  mult_numbers_name_2_arg;
	int  *result_3;
	num_arg_1  div_numbers_2_arg;
	int  *result_4;
	num_arg_3  div_numbers_name_2_arg;
	clnt = clnt_create(host, NUMBER, MULT_DIV, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = mult_numbers_2(&mult_numbers_2_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_2 = mult_numbers_name_2(&mult_numbers_name_2_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_3 = div_numbers_2(&div_numbers_2_arg, clnt);
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_4 = div_numbers_name_2(&div_numbers_name_2_arg, clnt);
	if (result_4 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


int main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	number_1( host );
//	number_2( host );
}
